apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ducnguyen96
  region: ap-southeast-1
  version: "1.21"

nodeGroups:
  - name: linux-nodes
    labels:
      role: workers
    instanceType: t3.small
    desiredCapacity: 2
