apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-postgres-depl
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-postgres
  template:
    metadata:
      labels:
        app: api-gateway-postgres
    spec:
      containers:
        - name: api-gateway-postgres
          image: postgres:13.4
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
        # - name: api-gateway-postgres-pgadmin
        #   image: dpage/pgadmin4
        #   ports:
        #     - containerPort: 80
        #   env:
        #     - name: PGADMIN_DEFAULT_EMAIL
        #       value: ducnguyen96@gmail.com
        #     - name: PGADMIN_DEFAULT_PASSWORD
        #       value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-postgres-srv
  namespace: ingress-nginx
spec:
  selector:
    app: api-gateway-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-gateway-db
#   namespace: ingress-nginx
# spec:
#   type: NodePort
#   selector:
#     app: api-gateway-postgres
#   ports:
#     - name: pgadmin
#       protocol: TCP
#       port: 80
#       targetPort: 80
